title: Mistakes were made
description: .... as all can see and I admit it

remote_theme: "mmistakes/so-simple-theme@3.2.0"

url: "https://www.nizzoli.net"
copyright: "&copy; me"
date_format: "%B %-d, %Y"
skin: "/assets/css/skins/dark.css"
logo: "/images/mars-logo.png"
read_time: true
words_per_minute: # 200
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

footer_links:
  - title: GitHub
    url: https://github.com/gabrielenizzoli
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
